# Generated by Django 4.0 on 2021-12-13 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_skill_image_alter_skill_is_key_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='skills',
        ),
    ]
