# Generated by Django 4.0.1 on 2022-01-07 21:15

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_userprofile_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True),
        ),
    ]
