# Generated by Django 4.0.1 on 2022-01-07 21:23

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_contactprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True),
        ),
    ]
