# Generated by Django 4.0.1 on 2022-01-18 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_contactprofile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactprofile',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
