# Generated by Django 4.0.1 on 2022-01-22 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_contactprofile_phone_number_portfolio_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['importance'], 'verbose_name': 'Portfolio', 'verbose_name_plural': 'Portfolio Profiles'},
        ),
        migrations.AddField(
            model_name='portfolio',
            name='importance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
