# Generated by Django 4.0.1 on 2022-02-04 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_messages_delete_contactprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name*'),
        ),
    ]
