# Generated by Django 4.0.2 on 2022-02-15 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_messages_phone_number_alter_messages_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['importance'], 'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['importance'], 'verbose_name': 'Certificate', 'verbose_name_plural': 'Certificates'},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['importance'], 'verbose_name': 'Portfolio', 'verbose_name_plural': 'Portfolio Projects'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['importance'], 'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['importance'], 'verbose_name': 'Testimonial', 'verbose_name_plural': 'Testimonials'},
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='is_key_skill',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='blog',
            name='importance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='importance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='importance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='importance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
