# Generated by Django 4.0.2 on 2022-03-04 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_blog_options_alter_certificate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='skills'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
